version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: quiz_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz-db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: quiz_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/quiz-db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: quiz_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
